# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Build and deploy ClubApp Frontend  React Client on Node.js Linux

defaults:
  run:
    working-directory: "src/Client/"

on:
  push:
    branches:
    - stage
    paths:
    - src/Client/**
    - .github/workflows/ClubApp.Frontend.Stage.Linux.yml
  pull_request:
    types:
    - ready_for_review
    - reopened
    paths:
    - src/Client/**
    - .github/workflows/ClubApp.Frontend.Stage.Linux.yml
  workflow_dispatch:
env:
  AZURE_WEBAPP_NAME: ClubAppReactClientStage
  AZURE_WEBAPP_PACKAGE_PATH: src/Client/build
  NODEJS_VERSION: 16.x
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}
          path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ${{ env.AZURE_WEBAPP_NAME }}

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ClubAppReactClientStage'
          slot-name: 'production'
          publish-profile: ${{ secrets.ClubAppReactClientStage }}
          package: .