# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
name: Frontend - Build and deploy to Azure Linux

on:
  push:
    branches:
    - main
    - stage
    paths:
    - src/Client/**
    - .github/workflows/ClubApp.Frontend.Linux.yml
  pull_request:
    types:
    - ready_for_review
    - ready_for_review
    - opened
    - synchronize
    - reopened
    paths:
    - src/Client/**
    - .github/workflows/ClubApp.Frontend.Stage.Linux.yml
    branches:
    - main
    - stage
  workflow_dispatch:

env:
  AZURE_WEBAPP_REACTCLIENT_NAME: ClubAppReactClientStage
  NODEJS_VERSION: 16.x
  WORKING_DIRECTORY: src/Client

jobs:   
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODEJS_VERSION }}

      - name: npm install, build, and test
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: ClubApp.Client.React
          path: ${{ env.WORKING_DIRECTORY }}/build
          if-no-files-found: error

  deploy_stage:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: Staging
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: ClubApp.Client.React
          path: ${{ env.WORKING_DIRECTORY }}/build

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_REACTCLIENT_NAME }}
          publish-profile: ${{ secrets.ClubApp_ClientReact_FFFF }}
          package: ${{ env.WORKING_DIRECTORY }}/build
          #The slot shoudld be Staging. However, it's not enough budget to Standard App Service Plan for mulitple deployment slot.
          #slot-name: Staging 
